# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 - main

resources:
  - repo: self

variables:
  dockerImageTag: '$(Build.BuildId)'

################################################
# Azure DevOps Build and Push to Docker Hub CI #
################################################

stages:
  - stage: BuildAndPushDockerImages
    displayName: 'Build and Push Docker Images to Registry'
    jobs:
    - job: BuildAndPushBackend
      displayName: 'Build and Push Backend Docker Image'
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub_registry'
          repository: 'abdmuksith/backend_azure_pipeline'
          command: 'buildAndPush'
          Dockerfile: '**backend-acc/Dockerfile'
          tags: '$(dockerImageTag)'

    - job: BuildAndPushFrontend
      displayName: 'Build and Push Frontend Docker Image'
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub_registry'
          repository: 'abdmuksith/frontend_azure_pipeline'
          command: 'buildAndPush'
          Dockerfile: '**frontend-acc/Dockerfile'
          tags: '$(dockerImageTag)'

########################
# Self-hosted Agent CD #
########################

  - stage: PullAndRunDockerImages
    displayName: 'Pull and Run Docker Images on Self-hosted Agent'
    pool:
      name: my_azure_vm_agent

###########
# Frontend
###########

    jobs:
    - job: ManageFrontendContainers
      displayName: 'Manage Frontend Containers'
      steps:
      - script: |
          docker stop acc_frontend_container
          docker rm -f acc_frontend_container
          docker pull abdmuksith/frontend_azure_pipeline:$(dockerImageTag)
          docker run -itd --name acc_frontend_container -p 8080:80 abdmuksith/frontend_azure_pipeline:$(dockerImageTag)

###########
# Backend
###########

    - job: ManageBackendContainers
      displayName: 'Manage Backend Containers'
      steps:
      - script: |
            docker stop acc_backend_container
            docker rm -f acc_backend_container
            docker pull abdmuksith/backend_azure_pipeline:$(dockerImageTag)
            docker run -itd --name acc_backend_container -p 3001:3001 abdmuksith/backend_azure_pipeline:$(dockerImageTag)
            echo 'currently available and runing containers'
            docker ps -a
            echo 'removeing all unused images'
            docker image prune -a -f
            echo 'listing all available docker images'
            docker images -a
            echo 'Docker Backend Containers URL https://accounts.back.opsdemo.xyz/'
            echo 'Docker Frontend Containers URL https://accounts.front.opsdemo.xyz/'
            echo 'Done CD process'