# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

###################################
# BACKEND
###################################

stages:
- stage: backBuild
  displayName: backend Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker_hub_registry'
        repository: 'abdmuksith/backend_azure_pipeline'
        command: 'buildAndPush'
        Dockerfile: '**backend-acc/Dockerfile'
        tags: '$(Build.BuildId)'

- stage: stopAndDeleteBackendContainers
  displayName: Stop and Delete backend Containers
  jobs:
  - job: StopAndDeleteBackend
    displayName: Stop and Delete backend Containers
    pool:
      vmImage: my_azure_vm_agent
    steps:
    - script: |
        pwd
        ls -lart
        docker stop $(docker ps -a --filter ancestor=abdmuksith/backend_azure_pipeline --filter "label=buildid<$(Build.BuildId)" -q) || true
        docker rm $(docker ps -a --filter ancestor=abdmuksith/backend_azure_pipeline --filter "label=buildid<$(Build.BuildId)" -q) || true
      displayName: 'Stop and Delete Containers backend containers'

- stage: deployBackendContainers
  displayName: Deploy Backend Containers
  dependsOn: stopAndDeleteBackendContainers
  jobs:
  - job: RunBackendContainers
    displayName: Run Docker Backend Containers
    pool:
      vmImage: my_azure_vm_agent
    steps:
    - script: |
        docker pull abdmuksith/backend_azure_pipeline:$(tag)
      displayName: 'Pull Last Build Backend Images'

    - script: |
        docker run -d --name backend_container -p 8080:8080 abdmuksith/backend_azure_pipeline:$(tag)
        echo "https://accounts.back.opsdemo.xyz/"
      displayName: 'Run Docker Backend Containers'

##############################
# FRONTEND
##############################

- stage: frontBuild
  displayName: frontend Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker_hub_registry'
        repository: 'abdmuksith/frontend_azure_pipeline'
        command: 'buildAndPush'
        Dockerfile: '**frontend-acc/Dockerfile'
        tags: '$(Build.BuildId)'

- stage: stopAndDeleteFrontendContainers
  displayName: Stop and Delete forntend Containers
  jobs:
  - job: StopAndDeleteForntend
    displayName: Stop and Delete forntend Containers
    pool:
      vmImage: my_azure_vm_agent
    steps:
    - script: |
        pwd
        ls -lart
        docker stop $(docker ps -a --filter ancestor=abdmuksith/frontend_azure_pipeline --filter "label=buildid<$(Build.BuildId)" -q) || true
        docker rm $(docker ps -a --filter ancestor=abdmuksith/frontend_azure_pipeline --filter "label=buildid<$(Build.BuildId)" -q) || true
      displayName: 'Stop and Delete forntend Containers'

- stage: deployFrontendContainers
  displayName: Deploy Frontend Containers
  dependsOn: stopAndDeleteFrontendContainers
  jobs:
  - job: RunFrontendContainers
    displayName: Run Docker Frontend Containers
    pool:
      vmImage: my_azure_vm_agent
    steps:
    - script: |
        docker pull abdmuksith/frontend_azure_pipeline:$(tag)
      displayName: 'Pull Last Build Frontend Images'

    - script: |
        docker run -d --name frontend_container -p 80:80 abdmuksith/frontend_azure_pipeline:$(tag)
        echo "https://accounts.front.opsdemo.xyz/"
      displayName: 'Run Docker Frontend Containers'