# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: backBuild
  displayName: backend Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker_hub_registry'
        repository: 'abdmuksith/backend_azure_pipeline'
        command: 'buildAndPush'
        Dockerfile: '**backend-acc/Dockerfile'

- stage: frontBuild
  displayName: frontend Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker_hub_registry'
        repository: 'abdmuksith/frontend_azure_pipeline'
        command: 'buildAndPush'
        Dockerfile: '**frontend-acc/Dockerfile'
