# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

###################################
# BACKEND
###################################

stages:
  - stage: backBuild
    displayName: Backend Build Image
    jobs:

    - job: BuildBackend
      displayName: Build Backend
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub_registry'
          repository: 'abdmuksith/backend_azure_pipeline'
          command: 'buildAndPush'
          Dockerfile: '**backend-acc/Dockerfile'
          tags: '$(tag)'

    - job: StopAndDeleteBackend
      displayName: Stop and Delete Backend Containers
      pool:
        name: my_azure_vm_agent
      steps:
      - script: |
          pwd
          ls -lart
          docker stop acc_backend_container || true
          docker rm acc_backend_container || true
          docker ps -a
        displayName: 'Stop and Delete Containers for Backend'

    - job: RunBackendContainers
      displayName: Run Docker Backend Containers
      pool:
        name: my_azure_vm_agent
      steps:
      - script: |
          docker pull abdmuksith/backend_azure_pipeline:$(tag)
        displayName: 'Pull Last Build Backend Images'

      - script: |
          docker run -d --name acc_backend_container -p 3001:3001 abdmuksith/backend_azure_pipeline:$(tag)
          docker image prune
          docker images -a
        displayName: 'Run Docker Backend Containers https://accounts.back.opsdemo.xyz/'

##############################
# FRONTEND
##############################

  - stage: frontBuild
    displayName: Frontend Build Image
    jobs:
    - job: BuildFrontend
      displayName: Build Frontend
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub_registry'
          repository: 'abdmuksith/frontend_azure_pipeline'
          command: 'buildAndPush'
          Dockerfile: '**frontend-acc/Dockerfile'
          tags: '$(tag)'

    - job: StopAndDeleteFrontend
      displayName: Stop and Delete Frontend Containers
      pool:
        name: my_azure_vm_agent
      steps:
      - script: |
          pwd
          ls -lart
          docker stop acc_frontend_container || true
          docker rm acc_frontend_container || true
          docker ps -a
        displayName: 'Stop and Delete Containers for Frontend'

    - job: RunFrontendContainers
      displayName: Run Docker Frontend Containers
      pool:
        name: my_azure_vm_agent
      steps:
      - script: |
          docker pull abdmuksith/frontend_azure_pipeline:$(tag)
        displayName: 'Pull Last Build Frontend Images'

      - script: |
          docker run -d --name acc_frontend_container -p 8080:80 abdmuksith/frontend_azure_pipeline:$(tag)
          docker image prune
          docker images -a
        displayName: 'Run Docker Frontend Containers https://accounts.front.opsdemo.xyz/'
