# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

#############################################
# Azure Runners Build and Push to Docker hub
#############################################

stages:
  - stage: BuildandPush
    displayName: BuildandPush Image
    jobs:

    - job: BuildandPush
      displayName: BuildandPush
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub_registry'
          repository: 'abdmuksith/backend_azure_pipeline'
          command: 'buildAndPush'
          Dockerfile: '**backend-acc/Dockerfile'
          tags: '$(tag)'
      - task: Docker@2
        inputs:
          containerRegistry: 'docker_hub_registry'
          repository: 'abdmuksith/frontend_azure_pipeline'
          command: 'buildAndPush'
          Dockerfile: '**frontend-acc/Dockerfile'
          tags: '$(tag)'

####################
# SELF HOSTED AGENT
####################

  - stage: PullandRun
    displayName: PullandRun DockerImages

    pool:
      name: my_azure_vm_agent

############
# FRONTEND
############

    jobs:
    - job: StopAndDeleteFrontend
      displayName: Stop and Delete Frontend Containers
      steps:
      - script: |
          pwd
          ls -lart
          docker stop acc_frontend_container
          docker rm -f acc_frontend_container
          docker pull abdmuksith/frontend_azure_pipeline:$(tag)
          docker run -itd --name acc_frontend_container -p 8080:80 abdmuksith/frontend_azure_pipeline:$(tag)
          echo 'check Docker Frontend Containers https://accounts.front.opsdemo.xyz/'

############
# BACKEND
############

    - job: StopAndDeleteBackend
      displayName: Stop and Delete Backend Containers
      steps:
      - script: |
          docker stop acc_backend_container
          docker rm -f acc_backend_container
          docker pull abdmuksith/backend_azure_pipeline:$(tag)
          docker run -itd --name acc_backend_container -p 3001:3001 abdmuksith/backend_azure_pipeline:$(tag)
          docker ps -a
          docker image prune -f
          docker images -a
          echo 'chek Docker Backend Containers https://accounts.back.opsdemo.xyz/'