# only mysql docker-compose.yml
version: '3.8'
services:
### MySQL Container
  mysql:
    build:
      context: ./
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: abdmuksith/accounts.module.mysql-img
    ports:
      - "${MYSQL_PORT}:3306"

