version: '3'

services:
  frontend-acc:
    build:
      context: /frontend-acc  
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - account-net

  backend-acc:
    build:
      context: /backend-acc
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - account-net

  mysql-acc:
    build:
      context: /mysql-acc
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    networks:
      - account-net

networks:
  acc-net:
    external: true